package(default_visibility = ["//visibility:public"])

load("//build_defs:ts.bzl", "c_ts_project")

c_ts_project(
    name = "history",
    deps = [
        "//js/common",
        "//js/corgi",
    ],
)

